pipelines/container-build.yaml, pipelines/fbc-fragment-build.yaml, pipelines/multi-arch-container-build.yaml, pipelines/vllm-cpu-container-build.yaml
- **fix boolean typo**
- **add pipelinerun-name as task param**
- **change how params are passed into the custom status task**
- **try a different way to pass params**
- **apply fix to slack notifier section**
- **cleaning up fbc-fragment spec**
- **fix target_branch source**
=> pipeline improvements during integration of fbc-fragment pipelineruns

.github/workflows/pipelinerun-replicator.yml, script/pipelinerun_replicator.sh
- **update pipelinerun_replicator to work with pipelineRef files**
- **add log messages for pipelineRef detection**
- **fix typo in pipelineRef detection**
- **make dry run true by default to prevent accidental runs**
=> update pipelinerun replicator

pipelineruns/fms-guardrails-orchestrator/.tekton/fms-guardrails-orchestrator-v2-19-push.yaml
this external component should be rhel9
=> revert guardrails back to rhel9

pipelines/container-build.yaml, pipelines/fbc-fragment-build.yaml, pipelines/multi-arch-container-build.yaml, pipelines/vllm-cpu-container-build.yaml
- **moving  blocks to the end**
- **moving rhoai-init task to a separate file**
=> pipeline reworking

pipelines/container-build.yaml, pipelines/fbc-fragment-build.yaml, pipelines/multi-arch-container-build.yaml, pipelines/vllm-cpu-container-build.yaml
- **moving  blocks to the end**
- **move rhoai-init to separate repo**
- **move over fbc-fragment and vllm pipelines to use taskref rhoai-init**
=> pipeline reworking 2.21

pipelineruns/notebooks/.tekton/odh-workbench-jupyter-trustyai-cpu-py311-ubi9-n-v2-21-push.yaml
=> add jupyter-trustyai-cpu-py311-ubi9-n-v2-21 pipeline

pipelineruns/modelmesh/.tekton/odh-modelmesh-v2-22-push.yaml, pipelineruns/trustyai-explainability/.tekton/odh-trustyai-service-v2-22-push.yaml
Reverts red-hat-data-services/konflux-central#153
=> Revert "2.22 build failures"

.tekton/container-build-pull-request.yaml, .tekton/multi-arch-container-build-pull-request.yaml, pipelineruns/guardrails-detectors/.tekton/fms-guardrails-hf-detectors-v2-22-push.yaml, pipelineruns/modelmesh/.tekton/odh-modelmesh-v2-22-push.yaml, pipelineruns/notebooks/.tekton/odh-pipeline-runtime-datascience-cpu-py311-ubi9-n-v2-22-push.yaml, pipelineruns/notebooks/.tekton/odh-pipeline-runtime-minimal-cpu-py311-ubi9-n-v2-22-push.yaml, pipelineruns/notebooks/.tekton/odh-pipeline-runtime-pytorch-cuda-py311-ubi9-n-v2-22-push.yaml, pipelineruns/notebooks/.tekton/odh-pipeline-runtime-pytorch-rocm-py311-ubi9-n-v2-22-push.yaml, pipelineruns/notebooks/.tekton/odh-pipeline-runtime-tensorflow-cuda-py311-ubi9-n-v2-22-push.yaml, pipelineruns/notebooks/.tekton/odh-pipeline-runtime-tensorflow-rocm-py311-ubi9-n-v2-22-push.yaml, pipelineruns/notebooks/.tekton/odh-workbench-codeserver-datascience-cpu-py311-ubi9-n-v2-22-push.yaml, pipelineruns/notebooks/.tekton/odh-workbench-jupyter-datascience-cpu-py311-ubi9-n-v2-22-push.yaml, pipelineruns/notebooks/.tekton/odh-workbench-jupyter-minimal-cpu-py311-ubi9-n-v2-22-push.yaml, pipelineruns/notebooks/.tekton/odh-workbench-jupyter-minimal-cuda-py311-ubi9-n-v2-22-push.yaml, pipelineruns/notebooks/.tekton/odh-workbench-jupyter-minimal-rocm-py311-ubi9-n-v2-22-push.yaml, pipelineruns/notebooks/.tekton/odh-workbench-jupyter-pytorch-cuda-py311-ubi9-n-v2-22-push.yaml, pipelineruns/notebooks/.tekton/odh-workbench-jupyter-pytorch-rocm-py311-ubi9-n-v2-22-push.yaml, pipelineruns/notebooks/.tekton/odh-workbench-jupyter-tensorflow-cuda-py311-ubi9-n-v2-22-push.yaml, pipelineruns/notebooks/.tekton/odh-workbench-jupyter-tensorflow-rocm-py311-ubi9-n-v2-22-push.yaml, pipelineruns/notebooks/.tekton/odh-workbench-jupyter-trustyai-cpu-py311-ubi9-n-v2-22-push.yaml, pipelineruns/odh-dashboard/.tekton/odh-dashboard-on-pull-request.yaml, pipelineruns/odh-dashboard/.tekton/odh-dashboard-v2-22-push.yaml, pipelineruns/rhods-operator/.tekton/odh-operator-v2-22-push.yaml, pipelineruns/trustyai-explainability/.tekton/odh-trustyai-service-v2-22-push.yaml, pipelineruns/vllm/.tekton/vllm-cpu-pull-request.yaml, pipelineruns/vllm/.tekton/vllm-cpu-v2-22-push.yaml, pipelines/multi-arch-container-build.yaml
based on https://github.com/red-hat-data-services/odh-dashboard/tree/sealights-poc-2.16
=> attempt to add sealights to multi-arch container build

pipelines/container-build.yaml, pipelines/fbc-fragment-build.yaml
- **change the image used to run the sealights script**
- **add sealights steps to fbc**
=> add sealights to fbc

pipelineruns/vllm/.tekton/vllm-cuda-pull-request.yaml, pipelineruns/vllm/.tekton/vllm-cuda-v2-21-push.yaml, pipelineruns/vllm/.tekton/vllm-rocm-pull-request.yaml, pipelineruns/vllm/.tekton/vllm-rocm-v2-21-push.yaml
- **bump vllm cuda to 0.9.0**
- **down vllm rocm to 0.8.4**
=> update vllm 2.21

pipelines/container-build.yaml, pipelines/fbc-fragment-build.yaml
- **Revert "modify how bundle gets updated with sealights components"**
- **update container-build with rhoai sealights task**
=> add sealights task

pipelines/container-build.yaml, pipelines/fbc-fragment-build.yaml, pipelines/multi-arch-container-build.yaml, pipelines/vllm-cpu-container-build.yaml
without rhoai-init task being pinned to a specific commit Conforma validations in Konflux
will not pass
=> pin rhoai-init tekton task to the last commit

pipelineruns/odh-dashboard/.tekton/odh-dashboard-on-pull-request.yaml, pipelineruns/odh-dashboard/.tekton/odh-dashboard-v2-22-push.yaml
part of https://issues.redhat.com/browse/RHOAIENG-27183
update the component name for odh-dashboard
=> update odh-dashboard sealights component name

pipelineruns/trustyai-service-operator/.tekton/odh-trustyai-service-operator-v2-22-push.yaml
same as #195 but for 2.22 to avoid regression
=> update used service account for odh-trustyai-service-operator

pipelineruns/trustyai-service-operator/.tekton/odh-trustyai-service-operator-v2-21-push.yaml
Reverts red-hat-data-services/konflux-central#195
=> Revert "update used service account for odh-trustyai-service-operator"

pipelines/fbc-fragment-build.yaml
=> fix missing line

pipelineruns/ml-metadata/.tekton/odh-mlmd-grpc-server-v2-24-push.yaml
part of https://issues.redhat.com/browse/RHOAIENG-27351
follow up on #252
=> fix odh-mlmd-grpc-server taskRunSpecs

pipelineruns/fms-guardrails-orchestrator/.tekton/odh-fms-guardrails-orchestrator-v2-24-push.yaml, pipelineruns/guardrails-detectors/.tekton/odh-built-in-detector-v2-24-push.yaml, pipelineruns/trustyai-service-operator/.tekton/odh-ta-lmes-driver-v2-24-push.yaml, pipelineruns/vllm-orchestrator-gateway/.tekton/odh-trustyai-vllm-orchestrator-gateway-v2-24-push.yaml
part of https://issues.redhat.com/browse/RHOAIENG-27351
follows up on #297
=> Migrate Trusty AI builds to multi-arch

pipelines/container-build.yaml, pipelines/fbc-fragment-build.yaml, pipelines/multi-arch-container-build.yaml, pipelines/vllm-cpu-container-build.yaml
https://issues.redhat.com/browse/RHOAIENG-30983
=> Wznoinsk rhoai 2.24 rhoaieng 30983 source build oci ta

renovate/pipelines-renovate.json
part of [RHOAIENG-31585](https://issues.redhat.com/browse/RHOAIENG-31585)
split from #321
this PR will enable renovate updates to pipelines in the main branch.
=> renovate pipelines in main branch

.github/workflows/sync-pipelineruns.yml, .github/workflows/update-repository-list.yml
part of https://issues.redhat.com/browse/RHOAIENG-31585
split from #321 
this PR adds the required logic to github actions to sync pipelineruns from the main branch.
=> add pipelineruns sync logic to github actions

pipelineruns/argo-workflows/.tekton/odh-data-science-pipelines-argo-argoexec-pull-request.yaml, pipelineruns/argo-workflows/.tekton/odh-data-science-pipelines-argo-workflowcontroller-pull-request.yaml
part of https://issues.redhat.com/browse/RHOAIENG-31585
componentName must be shorter than or equal to 63 characters
=> shorten data-science-pipelines component name

pipelines/container-build.yaml, pipelines/fbc-fragment-build.yaml, pipelines/multi-arch-container-build.yaml, pipelines/vllm-cpu-container-build.yaml
https://issues.redhat.com/browse/KFLUXSPRT-4548
=> bump buildah-* tekton task bundle version

pipelineruns/notebooks/.tekton/odh-workbench-codeserver-datascience-cpu-py311-v2-24-push.yaml, pipelineruns/notebooks/.tekton/odh-workbench-codeserver-datascience-cpu-py312-v2-24-push.yaml, pipelineruns/notebooks/.tekton/odh-workbench-jupyter-datascience-cpu-py311-v2-24-push.yaml, pipelineruns/notebooks/.tekton/odh-workbench-jupyter-datascience-cpu-py312-v2-24-push.yaml, pipelineruns/notebooks/.tekton/odh-workbench-jupyter-minimal-cpu-py311-v2-24-push.yaml, pipelineruns/notebooks/.tekton/odh-workbench-jupyter-minimal-cpu-py312-v2-24-push.yaml, pipelineruns/notebooks/.tekton/odh-workbench-jupyter-minimal-cuda-py311-v2-24-push.yaml, pipelineruns/notebooks/.tekton/odh-workbench-jupyter-minimal-cuda-py312-v2-24-push.yaml, pipelineruns/notebooks/.tekton/odh-workbench-jupyter-minimal-rocm-py311-v2-24-push.yaml, pipelineruns/notebooks/.tekton/odh-workbench-jupyter-minimal-rocm-py312-v2-24-push.yaml, pipelineruns/notebooks/.tekton/odh-workbench-jupyter-pytorch-cuda-py311-v2-24-push.yaml, pipelineruns/notebooks/.tekton/odh-workbench-jupyter-pytorch-cuda-py312-v2-24-push.yaml
https://issues.redhat.com/browse/RHOAIENG-31081
=> Move notebook images to internal konflux

pipelineruns/notebooks/.tekton/odh-pipeline-runtime-minimal-cpu-py312-pull-request.yaml
See this PR comment where it complains about it being an error:
https://github.com/red-hat-data-services/notebooks/pull/1445#issuecomment-3188176088
=> Remove invalid on-cel-expression

pipelineruns/notebooks/.tekton/odh-pipeline-runtime-datascience-cpu-py311-pull-request.yaml, pipelineruns/notebooks/.tekton/odh-pipeline-runtime-datascience-cpu-py312-pull-request.yaml, pipelineruns/notebooks/.tekton/odh-pipeline-runtime-minimal-cpu-py311-pull-request.yaml, pipelineruns/notebooks/.tekton/odh-pipeline-runtime-minimal-cpu-py312-pull-request.yaml, pipelineruns/notebooks/.tekton/odh-workbench-jupyter-datascience-cpu-py311-pull-request.yaml, pipelineruns/notebooks/.tekton/odh-workbench-jupyter-datascience-cpu-py312-pull-request.yaml, pipelineruns/notebooks/.tekton/odh-workbench-jupyter-minimal-cpu-py311-pull-request.yaml, pipelineruns/notebooks/.tekton/odh-workbench-jupyter-minimal-cpu-py312-pull-request.yaml
Adding linux/ppc64le build-platform for notebook images.
=> adding ppc64le build-platform for pipeline runs

pipelineruns/training-operator/.tekton/odh-training-operator-pull-request.yaml
Depends on: https://github.com/red-hat-data-services/training-operator/pull/553
=> (feat): Enable ARM builds for training-operator

pipelineruns/data-science-pipelines-operator/.tekton/odh-data-science-pipelines-operator-controller-pull-request.yaml
Depends on: https://github.com/red-hat-data-services/data-science-pipelines-operator/pull/504
=> (feat): Enable ARM builds for DSPO

pipelineruns/kuberay/.tekton/odh-kuberay-operator-controller-pull-request.yaml
Depends on: https://github.com/red-hat-data-services/kuberay/pull/546
=> (feat): Enable ARM builds for Kuberay

pipelineruns/feast/.tekton/odh-feast-operator-pull-request.yaml, pipelineruns/feast/.tekton/odh-feature-server-pull-request.yaml
Depends on: https://github.com/red-hat-data-services/feast/pull/83
=> (feast): Enable ARM builds for feast

pipelineruns/data-science-pipelines/.tekton/odh-ml-pipelines-api-server-v2-pull-request.yaml, pipelineruns/data-science-pipelines/.tekton/odh-ml-pipelines-driver-pull-request.yaml, pipelineruns/data-science-pipelines/.tekton/odh-ml-pipelines-launcher-pull-request.yaml, pipelineruns/data-science-pipelines/.tekton/odh-ml-pipelines-persistenceagent-v2-pull-request.yaml, pipelineruns/data-science-pipelines/.tekton/odh-ml-pipelines-scheduledworkflow-v2-pull-request.yaml
Depends on: https://github.com/red-hat-data-services/data-science-pipelines/pull/805
=> feat: Enable ARM DSP

pipelineruns/argo-workflows/.tekton/odh-data-science-pipelines-argo-argoexec-pull-request.yaml, pipelineruns/argo-workflows/.tekton/odh-data-science-pipelines-argo-workflowcontroller-pull-request.yaml
Depends on : https://github.com/red-hat-data-services/argo-workflows/pull/347
=> (feat): Enable ARM builds for argo-workflows

pipelineruns/vllm-orchestrator-gateway/.tekton/odh-trustyai-vllm-orchestrator-gateway-pull-request.yaml
depdends on https://github.com/red-hat-data-services/vllm-orchestrator-gateway/pull/16
=> enable ARM for odh-trustyai-vllm-orchestrator-gateway

pipelineruns/odh-dashboard/.tekton/odh-dashboard-v2-25-pull-request.yaml, pipelineruns/odh-dashboard/.tekton/odh-dashboard-v2-25-push.yaml
https://redhat-internal.slack.com/archives/C07ANR2U56C/p1756289548837369?thread_ts=1756286480.270329&cid=C07ANR2U56C
=> update prefetch-input paths

pipelineruns/notebooks/.tekton/odh-pipeline-runtime-datascience-cpu-py311-pull-request.yaml, pipelineruns/notebooks/.tekton/odh-pipeline-runtime-datascience-cpu-py312-pull-request.yaml, pipelineruns/notebooks/.tekton/odh-workbench-codeserver-datascience-cpu-py311-pull-request.yaml, pipelineruns/notebooks/.tekton/odh-workbench-codeserver-datascience-cpu-py312-pull-request.yaml, pipelineruns/notebooks/.tekton/odh-workbench-jupyter-datascience-cpu-py311-pull-request.yaml, pipelineruns/notebooks/.tekton/odh-workbench-jupyter-datascience-cpu-py312-pull-request.yaml, pipelineruns/notebooks/.tekton/odh-workbench-jupyter-trustyai-cpu-py311-pull-request.yaml, pipelineruns/notebooks/.tekton/odh-workbench-jupyter-trustyai-cpu-py312-pull-request.yaml
=> Add s390x to pull request pipelines

pipelines/multi-arch-container-build.yaml
Ref: https://redhat-internal.slack.com/archives/C04PZ7H0VA8/p1756852341080349?thread_ts=1756849346.657469&cid=C04PZ7H0VA8
=> upgrade to 0.2

.tekton/container-build-pull-request.yaml, canary-build/Dockerfile.konflux, pipelines/container-build.yaml, pipelines/fbc-fragment-build.yaml
initial step for resolving https://issues.redhat.com/browse/RHOAIENG-31966 
next steps:
- https://github.com/red-hat-data-services/RHOAI-Build-Config/pull/8838 
- and then update all konflux-central 2.16 pipelineruns to use pipeline spec
=> add container build pipeline and pull request pipeline into 2.16

pipelineruns/feast/.tekton/odh-feast-operator-v2-25-pull-request.yaml, pipelineruns/feast/.tekton/odh-feast-operator-v2-25-push.yaml, pipelineruns/feast/.tekton/odh-feature-server-v2-25-pull-request.yaml, pipelineruns/fms-guardrails-orchestrator/.tekton/odh-fms-guardrails-orchestrator-v2-25-pull-request.yaml, pipelineruns/fms-guardrails-orchestrator/.tekton/odh-fms-guardrails-orchestrator-v2-25-push.yaml, pipelineruns/guardrails-detectors/.tekton/odh-built-in-detector-v2-25-pull-request.yaml, pipelineruns/guardrails-detectors/.tekton/odh-built-in-detector-v2-25-push.yaml, pipelineruns/notebooks/.tekton/odh-pipeline-runtime-datascience-cpu-py312-v2-25-push.yaml, pipelineruns/trustyai-explainability/.tekton/odh-trustyai-service-v2-25-pull-request.yaml, pipelineruns/trustyai-explainability/.tekton/odh-trustyai-service-v2-25-push.yaml, pipelineruns/trustyai-service-operator/.tekton/odh-ta-lmes-driver-v2-25-pull-request.yaml, pipelineruns/trustyai-service-operator/.tekton/odh-ta-lmes-driver-v2-25-push.yaml, pipelineruns/trustyai-service-operator/.tekton/odh-trustyai-service-operator-v2-25-pull-request.yaml, pipelineruns/trustyai-service-operator/.tekton/odh-trustyai-service-operator-v2-25-push.yaml, pipelineruns/vllm-orchestrator-gateway/.tekton/odh-trustyai-vllm-orchestrator-gateway-v2-25-pull-request.yaml, pipelineruns/vllm-orchestrator-gateway/.tekton/odh-trustyai-vllm-orchestrator-gateway-v2-25-push.yaml
Enabling push and pull pipelines for some of the components.
=> enable pull/push pipelines for 2.25 components for ppc64le

pipelineruns/vllm/.tekton/odh-vllm-cuda-v2-25-push.yaml
Ref: https://redhat-internal.slack.com/archives/C07TF3MBMMW/p1757416368065659?thread_ts=1757411802.477599&cid=C07TF3MBMMW
=> drop arm64 platform

pipelines/multi-arch-container-build.yaml
Ref: https://redhat-internal.slack.com/archives/C04PZ7H0VA8/p1757947875690729?thread_ts=1756849346.657469&cid=C04PZ7H0VA8
=> Disable ecosystem-cert-preflight-checks task

pipelineruns/notebooks/.tekton/odh-workbench-jupyter-trustyai-cpu-py312-pull-request.yaml
Successful Arm build can be seen here: https://konflux-ui.apps.stone-prod-p02.hjvn.p1.openshiftapps.com/ns/rhoai-tenant/applications/automation/pipelineruns/odh-workbench-jupyter-trustyai-cpu-py312-on-pull-request-24b77
=> Build Trusty AI workbench image for Arm

script/apply-z-stream-changes.sh, script/pipelinerun_replicator.sh
use coorect variable for filename
=> update version in build-arguments for modelmesh

pipelineruns/llm-d-inference-scheduler/.tekton/odh-llm-d-inference-scheduler-v2-25-push.yaml
https://issues.redhat.com/browse/RHOAIENG-34216
=> add rhelai rpm repo to llm-d-inference-scheduler prefetch configuration

pipelineruns/rhods-operator/.tekton/odh-operator-pull-request.yaml
Corresponds to this PR where first rpm is added:
https://github.com/red-hat-data-services/rhods-operator/pull/12376
=> Prefetch rpm content for rhods-operator

pipelineruns/notebooks/.tekton/odh-pipeline-runtime-datascience-cpu-py312-v2-25-push.yaml, pipelineruns/notebooks/.tekton/odh-workbench-jupyter-datascience-cpu-py312-v2-25-push.yaml
Add s390x label for runtime datascience and jupyter datascience
=> Add s390x label for runtime and jupyter datascience

pipelines/fbc-fragment-build.yaml
This reverts commit e62dfeebbf543d1af96cc38688012443097a7702.
=> Revert "run fips check for fbc only for nightly pipeline runs"

pipelineruns/notebooks/.tekton/odh-workbench-codeserver-datascience-cpu-py312-v2-25-push.yaml
Reverts red-hat-data-services/konflux-central#715
=> Revert "[rhoai-2.25] Remove ppc64le arch from 2.25"

pipelineruns/feast/.tekton/odh-feature-server-v2-25-push.yaml
Extended prefetch-input configuration:
-   Included additional rpm dependencies.
-   Added generic path support for multicloud feature server.
=> Update Feature Server push pipeline for rhoai-2.25
