pipelineruns/ml-metadata/.tekton/odh-mlmd-grpc-server-v2-19-push.yaml
hermetic was set to false as part of ongoing 2.21 work. 2.21 pipelines were copied into 2.19 for the purposes of 2.19.1. hermetic should be set to true for 2.19
=> enable hermetic for ml-metadata

pipelineruns/argo-workflows/.tekton/odh-data-science-pipelines-argo-argoexec-v2-19-push.yaml, pipelineruns/argo-workflows/.tekton/odh-data-science-pipelines-argo-workflowcontroller-v2-19-push.yaml, pipelineruns/codeflare-operator/.tekton/odh-codeflare-operator-v2-19-push.yaml, pipelineruns/data-science-pipelines-operator/.tekton/odh-data-science-pipelines-operator-controller-v2-19-push.yaml, pipelineruns/data-science-pipelines/.tekton/odh-ml-pipelines-api-server-v2-v2-19-push.yaml, pipelineruns/data-science-pipelines/.tekton/odh-ml-pipelines-driver-v2-19-push.yaml, pipelineruns/data-science-pipelines/.tekton/odh-ml-pipelines-launcher-v2-19-push.yaml, pipelineruns/data-science-pipelines/.tekton/odh-ml-pipelines-persistenceagent-v2-v2-19-push.yaml, pipelineruns/data-science-pipelines/.tekton/odh-ml-pipelines-scheduledworkflow-v2-v2-19-push.yaml, pipelineruns/fms-guardrails-orchestrator/.tekton/fms-guardrails-orchestrator-v2-19-push.yaml, pipelineruns/ilab-on-ocp/.tekton/odh-ml-pipelines-runtime-generic-v2-19-push.yaml, pipelineruns/kubeflow/.tekton/odh-kf-notebook-controller-v2-19-push.yaml, pipelineruns/kubeflow/.tekton/odh-notebook-controller-v2-19-push.yaml, pipelineruns/kuberay/.tekton/odh-kuberay-operator-controller-v2-19-push.yaml, pipelineruns/kueue/.tekton/odh-kueue-controller-v2-19-push.yaml, pipelineruns/ml-metadata/.tekton/odh-mlmd-grpc-server-v2-19-push.yaml, pipelineruns/model-registry-operator/.tekton/odh-model-registry-operator-v2-19-push.yaml, pipelineruns/model-registry/.tekton/odh-model-registry-v2-19-push.yaml, pipelineruns/modelmesh-runtime-adapter/.tekton/odh-modelmesh-runtime-adapter-v2-19-push.yaml, pipelineruns/modelmesh-serving/.tekton/odh-modelmesh-serving-controller-v2-19-push.yaml, pipelineruns/modelmesh/.tekton/odh-modelmesh-v2-19-push.yaml, pipelineruns/odh-dashboard/.tekton/odh-dashboard-v2-19-push.yaml, pipelineruns/odh-model-controller/.tekton/odh-model-controller-v2-19-push.yaml, pipelineruns/rest-proxy/.tekton/odh-mm-rest-proxy-v2-19-push.yaml, pipelineruns/rhods-operator/.tekton/odh-operator-v2-19-push.yaml, pipelineruns/rhods-operator/.tekton/odh-operator-v2-19-scheduled.yaml, pipelineruns/training-operator/.tekton/odh-training-operator-v2-19-push.yaml, pipelineruns/trustyai-explainability/.tekton/odh-trustyai-service-v2-19-push.yaml, pipelineruns/trustyai-service-operator/.tekton/odh-trustyai-service-operator-v2-19-push.yaml
this was a side effect of copying over pipelines from 2.21 to 2.19
=> switch all quay targets back to rhel8

script/pipelinerun_replicator.sh
yq -i changes the formatting of the yaml output more than desired. Reverting back to the original sed method, adding a variant for the pipelineref case
related PR - https://github.com/red-hat-data-services/konflux-central/pull/84
=> replace usage of yq -i in replicator

pipelines/container-build.yaml
This is required for the Conforma checks
to pass, otherwise they highlight:
Task rhoai-init is used by pipeline task
rhoai-init via an unpinned reference.
=> pin rhoai-init tekton task to latest commit sha

renovate/default-renovate.json
we are past code freeze and dependency updates should stop to ease the effort to release.
=> stop renovate for rhoai-2.21

pipelineruns/trustyai-service-operator/.tekton/odh-trustyai-service-operator-v2-21-push.yaml
```
failed to create task run pod "odh-trustyai-service-operator-v2-21-on-push-xqqff-rhoai-init": translating TaskSpec to Pod: serviceaccounts "build-pipeline-odh-trustyai-service-operator-v2-21" not found. Maybe missing or invalid Task rhoai-tenant/
```
=> update used service account for odh-trustyai-service-operator

pipelineruns/argo-workflows/.tekton/odh-data-science-pipelines-argo-argoexec-v2-24-push.yaml, pipelineruns/argo-workflows/.tekton/odh-data-science-pipelines-argo-workflowcontroller-v2-24-push.yaml, pipelineruns/codeflare-operator/.tekton/odh-codeflare-operator-v2-24-push.yaml, pipelineruns/data-science-pipelines-operator/.tekton/odh-data-science-pipelines-operator-controller-v2-24-push.yaml, pipelineruns/data-science-pipelines/.tekton/odh-ml-pipelines-api-server-v2-v2-24-push.yaml, pipelineruns/data-science-pipelines/.tekton/odh-ml-pipelines-driver-v2-24-push.yaml, pipelineruns/data-science-pipelines/.tekton/odh-ml-pipelines-launcher-v2-24-push.yaml, pipelineruns/data-science-pipelines/.tekton/odh-ml-pipelines-persistenceagent-v2-v2-24-push.yaml, pipelineruns/data-science-pipelines/.tekton/odh-ml-pipelines-scheduledworkflow-v2-v2-24-push.yaml, pipelineruns/feast/.tekton/odh-feast-operator-v2-24-push.yaml, pipelineruns/feast/.tekton/odh-feature-server-v2-24-push.yaml, pipelineruns/ilab-on-ocp/.tekton/odh-ml-pipelines-runtime-generic-v2-24-push.yaml, pipelineruns/kubeflow/.tekton/odh-kf-notebook-controller-v2-24-push.yaml, pipelineruns/kubeflow/.tekton/odh-notebook-controller-v2-24-push.yaml, pipelineruns/kuberay/.tekton/odh-kuberay-operator-controller-v2-24-push.yaml, pipelineruns/kueue/.tekton/odh-kueue-controller-v2-24-push.yaml, pipelineruns/llama-stack-k8s-operator/.tekton/odh-llama-stack-k8s-operator-v2-24-push.yaml, pipelineruns/llm-d-inference-scheduler/.tekton/odh-llm-d-inference-scheduler-v2-24-push.yaml, pipelineruns/llm-d-routing-sidecar/.tekton/odh-llm-d-routing-sidecar-v2-24-push.yaml, pipelineruns/lm-evaluation-harness/.tekton/ta-lmes-job-v2-24-push.yaml, pipelineruns/ml-metadata/.tekton/odh-mlmd-grpc-server-v2-24-push.yaml, pipelineruns/model-registry-operator/.tekton/odh-model-registry-operator-v2-24-push.yaml, pipelineruns/model-registry/.tekton/odh-model-registry-v2-24-push.yaml, pipelineruns/modelmesh-runtime-adapter/.tekton/odh-modelmesh-runtime-adapter-v2-24-push.yaml, pipelineruns/modelmesh-serving/.tekton/odh-modelmesh-serving-controller-v2-24-push.yaml, pipelineruns/modelmesh/.tekton/odh-modelmesh-v2-24-push.yaml, pipelineruns/rest-proxy/.tekton/odh-mm-rest-proxy-v2-24-push.yaml, pipelineruns/training-operator/.tekton/odh-training-operator-v2-24-push.yaml, pipelineruns/trustyai-explainability/.tekton/odh-trustyai-service-v2-24-push.yaml, pipelineruns/trustyai-service-operator/.tekton/odh-trustyai-service-operator-v2-24-push.yaml
part of:
- https://issues.redhat.com/browse/RHOAIENG-27351
- https://issues.redhat.com/browse/RHOAIENG-28846
this PR changes all single-arch pipelines to multi-arch pipelines.
switch all pipelines to be multi-arch (use linux/x86_64 for build platform and set build-image-index to false)
when adding a 2nd platform - set build-image-index to true
in this PR we are enabling the different components to start working towards ARM support in their code, code dependencies and Dockerfiles/Containerfiles.
once ready, an addition of ARM build platform can be made, to enable ARM builds.
reference: https://konflux.pages.redhat.com/docs/users/getting-started/multi-platform-builds.html#multi-platform-build-vms-for-amd64-and-arm64
=> multi-arch pipelines migration (rhoai-2.24)

pipelineruns/README.md.in, pipelineruns/odh-dashboard/.tekton/odh-dashboard-pull-request.yaml
part of https://issues.redhat.com/browse/RHOAIENG-31585
split from #321 
in this PR we add a single pull-request pipeline to main for odh-dashboard.
from https://github.com/red-hat-data-services/konflux-central/pull/321#pullrequestreview-3093302454:
> Once we merge that, try out some pr pipelines in odh-dashboard and work out any kinks we find, we can PR the rest of the component repos
=> add odh-dashboard pipelinerun to main as a poc for pull-request pipelines

pipelineruns/fms-guardrails-orchestrator/.tekton/odh-fms-guardrails-orchestrator-pull-request.yaml
Depends on: https://github.com/red-hat-data-services/fms-guardrails-orchestrator/pull/30
=> (feat): Enable ARM builds for fms-guardrails-orchestrator

pipelineruns/trustyai-explainability/.tekton/odh-trustyai-service-pull-request.yaml, pipelineruns/trustyai-service-operator/.tekton/odh-ta-lmes-driver-pull-request.yaml, pipelineruns/trustyai-service-operator/.tekton/odh-trustyai-service-operator-pull-request.yaml, pipelineruns/vllm-orchestrator-gateway/.tekton/odh-trustyai-vllm-orchestrator-gateway-pull-request.yaml
Enabling pipelinerun for
- odh-trustyai-service-operator
- odh-trustyai-service
- odh-ta-lmes-driver
- odh-trustyai-vllm-orchestrator-gateway
=> Enable trustyai pipelinerun for ppc64le architecture

pipelineruns/fms-guardrails-orchestrator/.tekton/odh-fms-guardrails-orchestrator-pull-request.yaml, pipelineruns/guardrails-detectors/.tekton/odh-built-in-detector-pull-request.yaml, pipelineruns/guardrails-detectors/.tekton/odh-guardrails-detector-huggingface-runtime-pull-request.yaml, pipelineruns/lm-evaluation-harness/.tekton/odh-ta-lmes-job-pull-request.yaml, pipelineruns/trustyai-explainability/.tekton/odh-trustyai-service-pull-request.yaml, pipelineruns/trustyai-service-operator/.tekton/odh-ta-lmes-driver-pull-request.yaml, pipelineruns/trustyai-service-operator/.tekton/odh-trustyai-service-operator-pull-request.yaml, pipelineruns/vllm-orchestrator-gateway/.tekton/odh-trustyai-vllm-orchestrator-gateway-pull-request.yaml
Enabling pipelinerun for
- odh-trustyai-service-operator
- odh-trustyai-service
- odh-ta-lmes-driver
- odh-trustyai-vllm-orchestrator-gateway
- odh-fms-guardrails-orchestrator
- odh-built-in-detector
- odh-guardrails-detector-huggingface-runtime
- odh-ta-lmes-job
=> Enable trustyai pipelinerun for s390x architecture

pipelineruns/argo-workflows/.tekton/odh-data-science-pipelines-argo-argoexec-v2-25-pull-request.yaml, pipelineruns/argo-workflows/.tekton/odh-data-science-pipelines-argo-argoexec-v2-25-push.yaml, pipelineruns/argo-workflows/.tekton/odh-data-science-pipelines-argo-workflowcontroller-v2-25-pull-request.yaml, pipelineruns/argo-workflows/.tekton/odh-data-science-pipelines-argo-workflowcontroller-v2-25-push.yaml, pipelineruns/data-science-pipelines-operator/.tekton/odh-data-science-pipelines-operator-controller-v2-25-pull-request.yaml, pipelineruns/data-science-pipelines-operator/.tekton/odh-data-science-pipelines-operator-controller-v2-25-push.yaml, pipelineruns/data-science-pipelines/.tekton/odh-ml-pipelines-api-server-v2-v2-25-pull-request.yaml, pipelineruns/data-science-pipelines/.tekton/odh-ml-pipelines-api-server-v2-v2-25-push.yaml, pipelineruns/data-science-pipelines/.tekton/odh-ml-pipelines-driver-v2-25-pull-request.yaml, pipelineruns/data-science-pipelines/.tekton/odh-ml-pipelines-driver-v2-25-push.yaml, pipelineruns/data-science-pipelines/.tekton/odh-ml-pipelines-launcher-v2-25-pull-request.yaml, pipelineruns/data-science-pipelines/.tekton/odh-ml-pipelines-launcher-v2-25-push.yaml, pipelineruns/data-science-pipelines/.tekton/odh-ml-pipelines-persistenceagent-v2-v2-25-pull-request.yaml, pipelineruns/data-science-pipelines/.tekton/odh-ml-pipelines-persistenceagent-v2-v2-25-push.yaml, pipelineruns/data-science-pipelines/.tekton/odh-ml-pipelines-scheduledworkflow-v2-v2-25-pull-request.yaml, pipelineruns/data-science-pipelines/.tekton/odh-ml-pipelines-scheduledworkflow-v2-v2-25-push.yaml
Enabling pull and push pipelines for datascience pipeline images on IBM Power.
=> enable pull/push pipelines for datascience images on ppc64le

pipelineruns/notebooks/.tekton/odh-pipeline-runtime-pytorch-cuda-py312-v2-25-push.yaml, pipelineruns/notebooks/.tekton/odh-pipeline-runtime-pytorch-llmcompressor-cuda-py312-v2-25-push.yaml, pipelineruns/notebooks/.tekton/odh-pipeline-runtime-pytorch-rocm-py312-v2-25-push.yaml, pipelineruns/notebooks/.tekton/odh-pipeline-runtime-tensorflow-cuda-py312-v2-25-push.yaml, pipelineruns/notebooks/.tekton/odh-pipeline-runtime-tensorflow-rocm-py312-v2-25-push.yaml, pipelineruns/notebooks/.tekton/odh-workbench-codeserver-datascience-cpu-py312-v2-25-push.yaml, pipelineruns/notebooks/.tekton/odh-workbench-jupyter-datascience-cpu-py312-v2-25-push.yaml, pipelineruns/notebooks/.tekton/odh-workbench-jupyter-minimal-cuda-py312-v2-25-push.yaml, pipelineruns/notebooks/.tekton/odh-workbench-jupyter-minimal-rocm-py312-v2-25-push.yaml, pipelineruns/notebooks/.tekton/odh-workbench-jupyter-pytorch-cuda-py312-v2-25-push.yaml, pipelineruns/notebooks/.tekton/odh-workbench-jupyter-pytorch-llmcompressor-cuda-py312-v2-25-push.yaml, pipelineruns/notebooks/.tekton/odh-workbench-jupyter-pytorch-rocm-py312-v2-25-push.yaml, pipelineruns/notebooks/.tekton/odh-workbench-jupyter-tensorflow-cuda-py312-v2-25-push.yaml, pipelineruns/notebooks/.tekton/odh-workbench-jupyter-tensorflow-rocm-py312-v2-25-push.yaml, pipelineruns/notebooks/.tekton/odh-workbench-jupyter-trustyai-cpu-py312-v2-25-push.yaml
Ref: https://issues.redhat.com/browse/RHOAIENG-33925
As per the supported platforms listed [here](https://github.com/red-hat-data-services/notebooks/pull/1523#issuecomment-3271414392), updating the workbench pipelines to build for all target architectures. Builds will primarily use local platforms, since we [no longer need beefier remote VMs](https://redhat-internal.slack.com/archives/C07TF3MBMMW/p1757518575495799?thread_ts=1757435260.729159&cid=C07TF3MBMMW) becuase the components are already pre-built in the AIPCC base image instead of being built entirely from source.
=> Add target platforms as per RHOAIENG-33925

pipelineruns/notebooks/.tekton/odh-pipeline-runtime-pytorch-cuda-py312-v2-25-push.yaml, pipelineruns/notebooks/.tekton/odh-pipeline-runtime-pytorch-llmcompressor-cuda-py312-v2-25-push.yaml, pipelineruns/notebooks/.tekton/odh-workbench-jupyter-pytorch-cuda-py312-v2-25-push.yaml, pipelineruns/notebooks/.tekton/odh-workbench-jupyter-pytorch-llmcompressor-cuda-py312-v2-25-push.yaml
Related Slack thread: https://redhat-internal.slack.com/archives/C08PJ9XN3QR/p1757956223126409
=> Remove arm64 build platform from pytorch notebooks

pipelines/multi-arch-container-build.yaml
The SAST Coverity check is currently optional and significantly increases build time. It is being temporarily disabled to speed up the build process and will need to be re-enabled once it becomes a mandatory requirement.
=> disable optional sast coverity check

pipelineruns/vllm-rocm/.tekton/odh-vllm-rocm-v2-25-push.yaml
Ref: https://redhat-internal.slack.com/archives/C07TF3MBMMW/p1758017741719969?thread_ts=1757411802.477599&cid=C07TF3MBMMW
JIRA: https://issues.redhat.com/browse/RHOAIENG-30508
Since the vllm-rocm image is no longer built from source:
- A standard VM is sufficient (no need for a high-spec one)
- A regular repository clone can be used
- Fetching tags is no longer required
=> update vllm-rocm pipelinerun

pipelineruns/rhods-operator/.tekton/odh-operator-v3-0-push.yaml, pipelineruns/rhods-operator/.tekton/odh-operator-v3-0-scheduled.yaml
I broke it, sorry. It's not possible for us currently to test the builds on main of the rhods operator with PR jobs, so I wasn't able to test it.
This is a follow up to #619
=> Fix prefetch-input config in rhods-operator

pipelineruns/ilab-on-ocp/.tekton/odh-ml-pipelines-runtime-generic-v2-25-push.yaml
Updating push pipeline for runtime-generic image to add linux/ppc64le platform.
=> enable push pipeline for ppc64le runtime-generic image

pipelines/multi-arch-container-build.yaml
v0.3 ensures only one report is generated per platform. Previously in v0.2, duplicate reports could be created.
Resolves: https://issues.redhat.com/browse/KFLUXSPRT-5160
=> fix: prevent duplicate reports across platforms

pipelineruns/kueue/.tekton/odh-kueue-controller-v2-24-push.yaml
The decision has been made to not build s390x
images for odh-kueue-controller
in rhoai-2.24. It's been moved to rhoai-2.25.
https://redhat-internal.slack.com/archives/C07KPDHBR4J/p1755691723804839 https://issues.redhat.com/browse/RHOAIENG-31697
=> disable s390x builds for odh-kueue-controller

pipelineruns/feast/.tekton/odh-feature-server-v2-25-push.yaml
As per the list of components that should be built for Power for rhoai-2.25:
https://docs.google.com/spreadsheets/d/1R-Vc1ZKTyKOEYFTLmRlPnPqCVY5jbNvmrMEFUJrEnR4/edit?gid=1203748168#gid=1203748168
=> add ppc64le builds to feature server

pipelines/container-build.yaml, pipelines/multi-arch-container-build.yaml
Bump buildah task to 0.5 since 0.4 is archived and won't be trusted after 11 oct, 2025
=> Bump buildah remote oci ta

pipelineruns/notebooks/.tekton/odh-workbench-jupyter-trustyai-cpu-py312-v2-25-push.yaml
JIRA: https://issues.redhat.com/browse/RHOAIENG-34086
This was removed recently because it was thought that it wasn't currently possible to build it for Arm. It is, it just needed a dependency fix.
That fix is proposed here:
https://github.com/red-hat-data-services/notebooks/pull/1614
Once a decision has been made on whether to include this fix in 2.25 or not, both this PR and that notebooks PR should be merged in the correct order. I think the component change first, then this one.
=> Re-add arm64 to trustyai workbench build
